"""init

Revision ID: 45547486a33c
Revises: 
Create Date: 2026-05-14 17:28:40.434834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45547486a33c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('users_user_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['tg_user_id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_user_id_key'), 'users', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'tg_user_id')
    # ### end Alembic commands ###
